kshannon-ucsd/dsc40a

_data/wi25/staff.yml

adding profile pic to the shared drive

add json profile

---

_data/wi25/calendar.yml
_data/wi25/staff.yml
pages/resources.md

Added profile for Ansh, made small change to resources tab clarifying past lectures, and added link for welcome survey

Add ansh profile

---

_data/wi25/calendar.yml
pages/resources.md

1. Updated resources page with Utkarsh & Varun's videos
2. Moved Chapter notes to Week 2

Updating resources

---

_data/wi25/calendar.yml
pages/syllabus.md

1. changed weekly to bi-weekly on syllabus
2. Added tentative deadlines for homework on calendar
3. Clarification of groupwork & homework deadlines in syllabus

added tentative hw submission dates

---

_includes/week.html

Week.html wasn't updated to parse the submission button variable in the calendar yaml file.

Displaying Submission Button

---

_data/wi25/calendar.yml

gw1 solution & hw2 released

---

_data/wi25/calendar.yml
_includes/week.html

added overleaf template link and fixed study guide link formatting

hw3 links added

---

_data/wi25/calendar.yml

link fix for template, now has public access

template link fix

---

_data/wi25/calendar.yml

hops 7 link
hw 2 solution link
hw 3 date updated

updated links

---

_data/wi25/calendar.yml

hops 10 link

---

_data/wi25/calendar.yml
_includes/week.html

1. Added GW4 slides and problems link
2. Changed HTML to have slides links
3. Added GW3 problems link

Gw4 update

---

_data/wi25/calendar.yml

Just added GW3 solutions link.

groupwork 3 solutions link

---

_data/wi25/calendar.yml

updated HOPS 10, 11, 12 links

---

_data/wi25/calendar.yml

added hw3 and solutions
added gw4 solutions

hw3,4 and gw4 solutions

---

_config.yml
_data/demos.yml
_data/sp25/calendar.yml
_data/sp25/course.yml
_data/sp25/staff.yml
pages/calendar.md
pages/syllabus.md

This should be ready to go by the end of the week before spring break

Spring 2025

---

_data/sp25/staff.yml

I am not very sure whether i can use a link from google drive... just have a try

Update zimo's info for staff.yml

---

_data/sp25/staff.yml

Added appropriate details in Jack Determan's tutor bio.

Updated Jack Determan bio

---

_data/sp25/staff.yml

somewhat new to creating PRs but here's one. I updated Terran's staff description.

updated Terran's staff description

---

_data/sp25/calendar.yml

changed HOPS to HOPS 5 for HOPS 5

Fixed HOPS numbering

---

_data/sp25/calendar.yml

changed Estem link to campus wire

---

_data/sp25/calendar.yml

- hops 1 solutions
- hw1 due date to april 13

hops 1 sols and hw1 due date

---

_data/sp25/calendar.yml

Added shareable google drive link to pdf for HOPS 2.

Added link for HOPS2

---

_data/sp25/calendar.yml

- Added HOPS 3 problems to website
- Got rid of data link from last quarter's HOPS 3

Hops3 links

---

_data/sp25/calendar.yml

calendar change

---

_data/sp25/calendar.yml

hw2 pdf and code

---

_data/sp25/calendar.yml

hops 4 pdf and hops2 sols

---

_data/sp25/calendar.yml
_includes/week.html

- hops 5 pdf
- gw2 sols
- gw2 filled in by zimo
- homework released dates hidden

added hops5 and gw2 solutions

---

_data/sp25/calendar.yml

posted solutions oops

---

_data/sp25/calendar.yml

hops6 probs + code

---

_data/sp25/calendar.yml

gw2b problems

---

_data/sp25/calendar.yml

hops7 link

---

pages/syllabus.md

fixed syllabus typo

---

_data/sp25/calendar.yml

change gw names on calendar again

---

.github/workflows/jekyll.yml

Updated the commit value for ruby set-up to a the current latest commit value.

workflow warning fix

---

_data/sp25/calendar.yml

- added HOPS 6/7 sol links
- added HOPS 8 sols and problems

Gamblers fallacy

---

_data/sp25/calendar.yml

problems + code hops 9

---

_data/sp25/calendar.yml

- added HOPS 10 for conditional probability
- adjusted following HOPS numbers
- Removed commented solutions/links to clean up code

new HOPS 10

---

_data/sp25/calendar.yml

- added hw5 pdf link
- still waiting on template link

added hw5 pdf link

---

_data/sp25/calendar.yml

- added hops 12 pdf
- added hops 13 pdf

hops 12 and 13 links

---

_data/sp25/calendar.yml

- hops 11-13 solutions added
- small tweaks for looks (midterm review and gw4 walkthrough)

hops 11-13 solutions added
